---

- name: Install packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - git-core
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
  tags: packages
