---

- name: Install packages
  apt: pkg={{ item }} state=present update_cache=yes
  sudo: True
  with_items:
    - python-pip
    - python-dev
    - git-core
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - nfs-common
  tags: packages

