---

- name: mysql | Install mysql
  apt: 'name="mysql-server={{ mysql.version }}" state=present'
  sudo: True
  tags: sql

- name: mysql | Install mysql packages
  apt: name={{ item }} state=present
  sudo: True
  with_items:
    - mysql-client
    - libmysqlclient-dev
  tags: sql

- name: Mysql pip packages needed by ansible
  pip: name={{ item }} state=present
  sudo: True
  with_items:
    - MySQL-python

- name: mysql | Add application user
  sudo: True
  mysql_user: name=app host=% password=password login_user=root login_password=password
