---
- name: Installing apache2
  apt: 'name="apache2={{ apache_version }}" state=present'
  sudo: True
  tags: web

- name: Enable apache modules
  apache2_module: name={{ item }} state=present
  sudo: True
  tags: web
  with_items: apache_modules
  notify: restart apache2

- name: Set apache2 to use vagrant user and group
  lineinfile: dest=/etc/apache2/envvars regexp="^export {{ item }}=" line="export {{ item }}=vagrant
  with_items:
    - APACHE_RUN_USER
    - APACHE_RUN_GROUP

- name: Change owner on /etc/apache2 to vagrant
  file: path=/etc/apache2 recurse=yes owner=vagrant group=vagrant state=touch
  notify: restart apache2
